### ISSUE TITLE
Broken SMS API

### ISSUE THREAD

**Issue by StephenRUK** [mailjet/mailjet-apiv3-java#135] opened 2020-09-17 11:46 UTC
Hi!

I followed the example code for the SMS API, yet I am unable to send any messages. I have a valid token and enough funds on our account. Yet each request throws a MailjetException with HTTP 400.

Using the Postman examples and the same API token, I am able to send the same request. So it seems this utility is broken.

Analysis: I changed the URL and sent it to a mock REST API. **The MailJet client seems to send an empty body.**
 Can you please investigate and fix the SMS functionality?

**Comment by goacoustic** [comment] 2020-12-07 00:30
Hi @StephenRUK, thank you for raising this issue.

Seems like you were using the old wrapper version, v4.5.x. This version had an issue with the default connection timeout settings, which could result in closing a connection before the actual data is sent, so it seems like an empty body.

The issue is fixed in v4.6.x, that are available. Also, I've added integration tests to verify SMS functionality to omit such issues in the future 😊

**Closed** 2020-12-07 02:25 UTC
