### ISSUE TITLE
Type mismatch. Expected type \"Messages\"

### ISSUE THREAD

**Issue by sraza123** [mailjet/mailjet-apiv3-java#103] opened 2018-11-28 08:28 UTC
I am getting the following error with V3.1 API when trying to send out the email

Error: {"Errors":[{"ErrorIdentifier":"6414ac22-bf39-47a3-8ed3-1dee18546902","ErrorCode":"mj-0004","ErrorRelatedTo":["Messages"],"ErrorMessage":"Type mismatch. Expected type \"Messages\".","StatusCode":400},{"ErrorIdentifier":"24ff204b-6b41-44b6-b17a-94eeafd5e964","ErrorCode":"mj-0003","ErrorRelatedTo":["Messages"],"ErrorMessage":"Missing mandatory property.","StatusCode":400}],"Messages":[]}

Request Body

MailjetRequest request = new MailjetRequest(Emailv31.resource)
                                .property(Emailv31.MESSAGES, (new JSONArray())
                                .put(new JSONObject()
                                .put(Emailv31.Message.FROM, new JSONObject()
                                        .put("Email", "abc@abc.com")
                                        .put("Name", "Mailjet Pilot"))
                                .put(Emailv31.Message.TO, new JSONArray()
                                        .put(new JSONObject()
                                                .put("Email", "xyz@xyz.com")
                                                .put("Name",  "passenger 1")))
                                .put(Emailv31.Message.TEMPLATELANGUAGE, true)
                                .put(Emailv31.Message.TEMPLATEID, 123456)
                                .put(Emailv31.Message.SUBJECT, "Your email flight plan!")
                                .put(Emailv31.Message.VARIABLES, new JSONObject()
                                        .put("test", "test"
                                ))));

**Comment by todorDim** [comment] 2019-02-20 13:32
Hello @sraza123,

I will checkout what's going on and get back to you.

Regards,
T.

**Comment by Nikola-Andreev** [comment] 2019-04-09 09:05
Hi @sraza123 
There must be something wrong with your template, because the request is valid. I tried the same request with another emails and it is working fine. If you can provide details about the template and we will check again.

Regards.

**Comment by goacoustic** [comment] 2020-10-21 23:29
Seems like the issue is outdated, right now request is working fine. Going to close it.

**Closed by goacoustic** 2020-10-21 23:29 UTC
